import crypto from "node:crypto";
import { ColliderClient } from "../collider/client.js";
import { displayUnitsToBaseUnitsString, normalizeAssetsMetaPayload } from "./assets-meta.js";
import { DOCTRINE_PACK_PRESETS, type DoctrinePackId } from "./agent-profile.js";
import {
  BETA_TEST_TOKEN_AMOUNT,
  BETA_TEST_TOKEN_AMOUNT_DISPLAY,
  BETA_USDC_ASSET,
  BETA_DEFAULT_THROW_AMOUNT,
  BETA_DEFAULT_THROW_AMOUNT_DISPLAY,
  normalizeSettings,
  saveSettings,
  type AgentSettings,
} from "./settings.js";

export type AgentBootstrapSummary = {
  profile: "beta_auto";
  startupMode: "zero_flag_beta";
  tokenState: "pending" | "requested" | "failed";
  startCommand: string;
  starterQuestion: string;
  starterStyles: Array<{
    promptLabel: "baseline" | "careful" | "stubborn" | "exploratory" | "hybrid";
    doctrinePack: DoctrinePackId;
    doctrineLabel: string;
    summary: string;
  }>;
  user: string | null;
  asset: string;
  amount: string;
  autoGeneratedUser: boolean;
  requestedTestTokensAt: string | null;
  requestTestTokensFailedAt: string | null;
  requestTestTokensFailure: string | null;
  welcomePending: boolean;
  humanLearning: {
    enabled: boolean;
    learnOwnManualThrows: boolean;
    trackedAddresses: string[];
    maxSeedsPerCycle: number | null;
  };
};

const STARTER_QUESTION =
  "How would you like me to play from here: baseline, careful, stubborn, exploratory, or hybrid?";

const STARTER_STYLE_CHOICES: Array<{
  promptLabel: "baseline" | "careful" | "stubborn" | "exploratory" | "hybrid";
  doctrinePack: DoctrinePackId;
}> = [
  { promptLabel: "baseline", doctrinePack: "baseline" },
  { promptLabel: "careful", doctrinePack: "peanut" },
  { promptLabel: "stubborn", doctrinePack: "tough_nut" },
  { promptLabel: "exploratory", doctrinePack: "nutjob" },
  { promptLabel: "hybrid", doctrinePack: "prof_deez_nutz" },
];

function cleanHex(value: unknown): string {
  return String(value ?? "").trim().replace(/^0x/i, "").toLowerCase();
}

function with0x(value: unknown): string {
  const cleaned = cleanHex(value);
  return cleaned ? `0x${cleaned}` : "";
}

export function generateRandomHex32(): string {
  return crypto.randomBytes(32).toString("hex");
}

async function fetchLiveAssetMeta(client: ColliderClient): Promise<Record<string, { asset: string; symbol: string; decimals: number }>> {
  try {
    return normalizeAssetsMetaPayload(await client.getAssetsMeta());
  } catch {
    return {};
  }
}

function resolveBootstrapRawAmount(asset: string, displayAmount: string, assetMeta: Record<string, { decimals: number }>, fallbackRaw: string): string {
  const normalizedAsset = cleanHex(asset);
  const decimals = Number(assetMeta?.[normalizedAsset]?.decimals);
  if (Number.isFinite(decimals) && decimals >= 0) {
    const converted = displayUnitsToBaseUnitsString(displayAmount, decimals);
    if (converted) return converted;
  }
  return fallbackRaw;
}

export function buildBootstrapSummary(settings: AgentSettings): AgentBootstrapSummary {
  const normalized = normalizeSettings(settings);
  const trackedAddresses = [
    ...(normalized.humanLearning?.addresses ?? []),
    normalized.humanLearning?.learnOwnManualThrows ? cleanHex(normalized.user) : "",
  ].map(cleanHex).filter(Boolean);
  const uniqueTrackedAddresses = [...new Set(trackedAddresses)];
  const tokenState = normalized.onboarding?.requestedTestTokensAt
    ? "requested"
    : normalized.onboarding?.requestTestTokensFailedAt
      ? "failed"
      : "pending";
  return {
    profile: "beta_auto",
    startupMode: "zero_flag_beta",
    tokenState,
    startCommand: "npm start",
    starterQuestion: STARTER_QUESTION,
    starterStyles: STARTER_STYLE_CHOICES.map((entry) => ({
      promptLabel: entry.promptLabel,
      doctrinePack: entry.doctrinePack,
      doctrineLabel: DOCTRINE_PACK_PRESETS[entry.doctrinePack].label,
      summary: DOCTRINE_PACK_PRESETS[entry.doctrinePack].summary,
    })),
    user: cleanHex(normalized.user) || null,
    asset: cleanHex(normalized.asset),
    amount: String(normalized.amount || BETA_DEFAULT_THROW_AMOUNT),
    autoGeneratedUser: !!normalized.onboarding?.autoGeneratedUser,
    requestedTestTokensAt: normalized.onboarding?.requestedTestTokensAt ?? null,
    requestTestTokensFailedAt: normalized.onboarding?.requestTestTokensFailedAt ?? null,
    requestTestTokensFailure: normalized.onboarding?.requestTestTokensFailure ?? null,
    welcomePending: !normalized.onboarding?.welcomeDismissedAt,
    humanLearning: {
      enabled: !!normalized.humanLearning?.enabled,
      learnOwnManualThrows: !!normalized.humanLearning?.learnOwnManualThrows,
      trackedAddresses: uniqueTrackedAddresses,
      maxSeedsPerCycle: normalized.humanLearning?.maxSeedsPerCycle ?? null,
    },
  };
}

export async function ensureBetaBootstrap(settings: AgentSettings, dataDir: string): Promise<AgentSettings> {
  let next = normalizeSettings(settings);
  const ts = new Date().toISOString();
  let changed = false;
  const bootstrapClient = new ColliderClient(next.rpc);
  const liveAssetMeta = await fetchLiveAssetMeta(bootstrapClient);

  if (!cleanHex(next.asset)) {
    next.asset = BETA_USDC_ASSET;
    changed = true;
  }
  if (!String(next.amount || "").trim() || cleanHex(next.asset) === BETA_USDC_ASSET && String(next.amount || "") === BETA_DEFAULT_THROW_AMOUNT) {
    next.amount = resolveBootstrapRawAmount(next.asset, BETA_DEFAULT_THROW_AMOUNT_DISPLAY, liveAssetMeta, BETA_DEFAULT_THROW_AMOUNT);
    changed = true;
  }
  if (!Array.isArray(next.allowedAssets) || next.allowedAssets.length === 0) {
    next.allowedAssets = [BETA_USDC_ASSET];
    changed = true;
  }

  if (!cleanHex(next.user)) {
    next.user = generateRandomHex32();
    next.onboarding = {
      ...(next.onboarding ?? {}),
      profile: "beta_auto",
      bootstrapVersion: Number(next.onboarding?.bootstrapVersion ?? 1) || 1,
      autoGeneratedUser: true,
      bootstrappedAt: next.onboarding?.bootstrappedAt ?? ts,
      requestedTestTokensAt: next.onboarding?.requestedTestTokensAt ?? null,
      requestTestTokensFailedAt: next.onboarding?.requestTestTokensFailedAt ?? null,
      requestTestTokensFailure: next.onboarding?.requestTestTokensFailure ?? null,
      welcomeDismissedAt: next.onboarding?.welcomeDismissedAt ?? null,
    };
    changed = true;
  }

  if (changed) {
    next = normalizeSettings(next);
    await saveSettings(next, dataDir);
  }

  if (
    next.onboarding?.autoGeneratedUser
    && cleanHex(next.user)
    && cleanHex(next.asset)
    && !next.onboarding?.requestedTestTokensAt
  ) {
    try {
      const requestAmount = resolveBootstrapRawAmount(next.asset, BETA_TEST_TOKEN_AMOUNT_DISPLAY, liveAssetMeta, BETA_TEST_TOKEN_AMOUNT);
      await bootstrapClient.mirrorDeposit(
        with0x(next.asset),
        with0x(next.user),
        requestAmount,
        with0x(generateRandomHex32()),
      );
      next = normalizeSettings({
        ...next,
        onboarding: {
          profile: "beta_auto",
          bootstrapVersion: Number(next.onboarding?.bootstrapVersion ?? 1) || 1,
          autoGeneratedUser: !!next.onboarding?.autoGeneratedUser,
          bootstrappedAt: next.onboarding?.bootstrappedAt ?? ts,
          requestedTestTokensAt: ts,
          requestTestTokensFailedAt: null,
          requestTestTokensFailure: null,
          welcomeDismissedAt: next.onboarding?.welcomeDismissedAt ?? null,
        },
      });
      await saveSettings(next, dataDir);
      console.log(`[bootstrap] requested beta test tokens for ${with0x(next.user)}`);
    } catch (err) {
      next = normalizeSettings({
        ...next,
        onboarding: {
          profile: "beta_auto",
          bootstrapVersion: Number(next.onboarding?.bootstrapVersion ?? 1) || 1,
          autoGeneratedUser: !!next.onboarding?.autoGeneratedUser,
          bootstrappedAt: next.onboarding?.bootstrappedAt ?? ts,
          requestedTestTokensAt: next.onboarding?.requestedTestTokensAt ?? null,
          requestTestTokensFailedAt: ts,
          requestTestTokensFailure: String(err),
          welcomeDismissedAt: next.onboarding?.welcomeDismissedAt ?? null,
        },
      });
      await saveSettings(next, dataDir);
      console.warn(`[bootstrap] test-token request failed for ${with0x(next.user)}:`, err);
    }
  }

  return next;
}
