import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { DoctrinePackId, GoalWeights } from "./agent-profile.js";

export const BETA_USDC_ASSET = "0101010101010101010101010101010101010101010101010101010101010101";
export const BETA_CLC_ASSET = "0303030303030303030303030303030303030303030303030303030303030303";
export const BETA_DEFAULT_THROW_AMOUNT = "1100000000";
export const BETA_TEST_TOKEN_AMOUNT = "100000000000";

export type AgentOnboardingSettings = {
  profile: "beta_auto";
  bootstrapVersion: number;
  autoGeneratedUser: boolean;
  bootstrappedAt: string | null;
  requestedTestTokensAt: string | null;
  requestTestTokensFailedAt: string | null;
  requestTestTokensFailure: string | null;
  welcomeDismissedAt: string | null;
};

export type HumanLearningSettings = {
  enabled: boolean;
  learnOwnManualThrows: boolean;
  addresses: string[];
  maxSeedsPerCycle: number | null;
};

export type AgentSettings = {
  rpc: string;
  wasm: string;
  user: string;
  asset: string;
  amount: string;
  maxCandidates: number;
  maxMs: number;
  pollMs: number;
  maxThrowsPerGame: number;
  maxThrowsPerSession: number;
  minMillisBetweenLiveThrows: number;
  monitorPort: number;
  minGameStakeUsd?: number | null;
  maxSingleThrowUsd?: number | null;
  maxGameExposureUsd?: number | null;
  minThrowUsd?: number | null;
  maxThrowUsd?: number | null;
  riskMode?: "defensive" | "balanced" | "aggressive";
  doctrinePack?: DoctrinePackId | null;
  goalWeights?: GoalWeights | null;
  customStrategy?: string | null;
  copySlammerWhenSameHoleType?: boolean;
  allowedAssets?: string[];
  blockedAssets?: string[];
  reserveBalanceBase?: string;
  targetBalanceUsd?: number | null;
  targetProfitUsd?: number | null;
  keepAssets?: string[];
  disposeAssets?: string[];
  baselineResetThrows?: number | null;
  onboarding?: AgentOnboardingSettings | null;
  humanLearning?: HumanLearningSettings | null;
};

export const DEFAULT_ONBOARDING_SETTINGS: AgentOnboardingSettings = {
  profile: "beta_auto",
  bootstrapVersion: 1,
  autoGeneratedUser: false,
  bootstrappedAt: null,
  requestedTestTokensAt: null,
  requestTestTokensFailedAt: null,
  requestTestTokensFailure: null,
  welcomeDismissedAt: null,
};

export const DEFAULT_HUMAN_LEARNING_SETTINGS: HumanLearningSettings = {
  enabled: true,
  learnOwnManualThrows: true,
  addresses: [],
  maxSeedsPerCycle: 12,
};

export const DEFAULT_SETTINGS: AgentSettings = {
  rpc: "https://v2.cryptocollider.com:4430/ext/bc/WdFeSwHfau9U7Vj8B1wEHhNMtubRQKfVGiuJwgTyDUBLbCH4s/collider_v2",
  wasm: "./assets/sim_core.wasm",
  user: "",
  asset: BETA_USDC_ASSET,
  amount: BETA_DEFAULT_THROW_AMOUNT,
  maxCandidates: 150,
  maxMs: 20000,
  pollMs: 15000,
  maxThrowsPerGame: 50,
  maxThrowsPerSession: 5000,
  minMillisBetweenLiveThrows: 20000,
  monitorPort: 8787,
  minGameStakeUsd: 0,
  maxSingleThrowUsd: 12,
  maxGameExposureUsd: 20000,
  minThrowUsd: 11,
  maxThrowUsd: 100,
  riskMode: "balanced",
  doctrinePack: "baseline",
  goalWeights: null,
  customStrategy: null,
  copySlammerWhenSameHoleType: false,
  allowedAssets: [BETA_USDC_ASSET],
  blockedAssets: [],
  reserveBalanceBase: "0",
  targetBalanceUsd: null,
  targetProfitUsd: null,
  keepAssets: [BETA_CLC_ASSET],
  disposeAssets: [],
  baselineResetThrows: 24,
  onboarding: { ...DEFAULT_ONBOARDING_SETTINGS },
  humanLearning: { ...DEFAULT_HUMAN_LEARNING_SETTINGS },
};

function normalizeStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((entry) => String(entry ?? "").trim()).filter(Boolean);
}

function normalizeNullableNumber(value: unknown): number | null {
  if (value == null || value === "") return null;
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : null;
}

function normalizeNullableString(value: unknown): string | null {
  const trimmed = String(value ?? "").trim();
  return trimmed ? trimmed : null;
}

function normalizeOnboardingSettings(value: Partial<AgentOnboardingSettings> | null | undefined): AgentOnboardingSettings {
  return {
    ...DEFAULT_ONBOARDING_SETTINGS,
    ...(value ?? {}),
    profile: "beta_auto",
    bootstrapVersion: Number(value?.bootstrapVersion ?? DEFAULT_ONBOARDING_SETTINGS.bootstrapVersion) || DEFAULT_ONBOARDING_SETTINGS.bootstrapVersion,
    autoGeneratedUser: !!value?.autoGeneratedUser,
    bootstrappedAt: normalizeNullableString(value?.bootstrappedAt),
    requestedTestTokensAt: normalizeNullableString(value?.requestedTestTokensAt),
    requestTestTokensFailedAt: normalizeNullableString(value?.requestTestTokensFailedAt),
    requestTestTokensFailure: normalizeNullableString(value?.requestTestTokensFailure),
    welcomeDismissedAt: normalizeNullableString(value?.welcomeDismissedAt),
  };
}

function normalizeHumanLearningSettings(value: Partial<HumanLearningSettings> | null | undefined): HumanLearningSettings {
  return {
    ...DEFAULT_HUMAN_LEARNING_SETTINGS,
    ...(value ?? {}),
    enabled: value?.enabled == null ? DEFAULT_HUMAN_LEARNING_SETTINGS.enabled : !!value.enabled,
    learnOwnManualThrows: value?.learnOwnManualThrows == null
      ? DEFAULT_HUMAN_LEARNING_SETTINGS.learnOwnManualThrows
      : !!value.learnOwnManualThrows,
    addresses: normalizeStringArray(value?.addresses),
    maxSeedsPerCycle: normalizeNullableNumber(value?.maxSeedsPerCycle) ?? DEFAULT_HUMAN_LEARNING_SETTINGS.maxSeedsPerCycle,
  };
}

export function normalizeSettings(settings: Partial<AgentSettings> | null | undefined): AgentSettings {
  const allowedAssets = normalizeStringArray(settings?.allowedAssets);
  return {
    ...DEFAULT_SETTINGS,
    ...(settings ?? {}),
    rpc: String(settings?.rpc ?? DEFAULT_SETTINGS.rpc).trim(),
    wasm: String(settings?.wasm ?? DEFAULT_SETTINGS.wasm).trim(),
    user: String(settings?.user ?? DEFAULT_SETTINGS.user).trim(),
    asset: String(settings?.asset ?? DEFAULT_SETTINGS.asset).trim(),
    amount: String(settings?.amount ?? DEFAULT_SETTINGS.amount).trim(),
    maxCandidates: Number(settings?.maxCandidates ?? DEFAULT_SETTINGS.maxCandidates) || DEFAULT_SETTINGS.maxCandidates,
    maxMs: Number(settings?.maxMs ?? DEFAULT_SETTINGS.maxMs) || DEFAULT_SETTINGS.maxMs,
    pollMs: Number(settings?.pollMs ?? DEFAULT_SETTINGS.pollMs) || DEFAULT_SETTINGS.pollMs,
    maxThrowsPerGame: Number(settings?.maxThrowsPerGame ?? DEFAULT_SETTINGS.maxThrowsPerGame) || DEFAULT_SETTINGS.maxThrowsPerGame,
    maxThrowsPerSession: Number(settings?.maxThrowsPerSession ?? DEFAULT_SETTINGS.maxThrowsPerSession) || DEFAULT_SETTINGS.maxThrowsPerSession,
    minMillisBetweenLiveThrows: Number(settings?.minMillisBetweenLiveThrows ?? DEFAULT_SETTINGS.minMillisBetweenLiveThrows) || DEFAULT_SETTINGS.minMillisBetweenLiveThrows,
    monitorPort: Number(settings?.monitorPort ?? DEFAULT_SETTINGS.monitorPort) || DEFAULT_SETTINGS.monitorPort,
    minGameStakeUsd: normalizeNullableNumber(settings?.minGameStakeUsd),
    maxSingleThrowUsd: normalizeNullableNumber(settings?.maxSingleThrowUsd),
    maxGameExposureUsd: normalizeNullableNumber(settings?.maxGameExposureUsd),
    minThrowUsd: normalizeNullableNumber(settings?.minThrowUsd),
    maxThrowUsd: normalizeNullableNumber(settings?.maxThrowUsd),
    riskMode: settings?.riskMode ?? DEFAULT_SETTINGS.riskMode,
    doctrinePack: settings?.doctrinePack ?? DEFAULT_SETTINGS.doctrinePack,
    goalWeights: settings?.goalWeights ?? DEFAULT_SETTINGS.goalWeights,
    customStrategy: normalizeNullableString(settings?.customStrategy),
    copySlammerWhenSameHoleType: settings?.copySlammerWhenSameHoleType == null
      ? !!DEFAULT_SETTINGS.copySlammerWhenSameHoleType
      : !!settings.copySlammerWhenSameHoleType,
    allowedAssets: allowedAssets.length ? allowedAssets : [...(DEFAULT_SETTINGS.allowedAssets ?? [])],
    blockedAssets: normalizeStringArray(settings?.blockedAssets),
    reserveBalanceBase: String(settings?.reserveBalanceBase ?? DEFAULT_SETTINGS.reserveBalanceBase ?? "0").trim() || "0",
    targetBalanceUsd: normalizeNullableNumber(settings?.targetBalanceUsd),
    targetProfitUsd: normalizeNullableNumber(settings?.targetProfitUsd),
    keepAssets: normalizeStringArray(settings?.keepAssets),
    disposeAssets: normalizeStringArray(settings?.disposeAssets),
    baselineResetThrows: normalizeNullableNumber(settings?.baselineResetThrows) ?? DEFAULT_SETTINGS.baselineResetThrows,
    onboarding: normalizeOnboardingSettings(settings?.onboarding),
    humanLearning: normalizeHumanLearningSettings(settings?.humanLearning),
  };
}

export async function loadSettings(dataDir = "./data"): Promise<AgentSettings> {
  await mkdir(dataDir, { recursive: true });
  const file = path.join(dataDir, "settings.json");

  try {
    const txt = await readFile(file, "utf8");
    const parsed = JSON.parse(txt) as Partial<AgentSettings>;
    return normalizeSettings(parsed);
  } catch {
    await saveSettings(DEFAULT_SETTINGS, dataDir);
    return normalizeSettings(DEFAULT_SETTINGS);
  }
}

export async function saveSettings(settings: AgentSettings, dataDir = "./data"): Promise<void> {
  await mkdir(dataDir, { recursive: true });
  const file = path.join(dataDir, "settings.json");
  await writeFile(file, JSON.stringify(normalizeSettings(settings), null, 2), "utf8");
}
